---
inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rubycw
  - rubocop-thread_safety

AllCops:
  CacheRootDirectory: 'tmp/'
  DefaultFormatter: fuubar
  DisabledByDefault: false
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  MaxFilesInCache: 65536
  NewCops: enable
  TargetRubyVersion: 3.2
  UseCache: true
  Include:
    - 'Gemfile'
    - 'Rakefile'
    - 'app/**/*.rb'
    - 'config.ru'
    - 'config/**/*.rb'
    - 'db/**/*.rb'
  Exclude:
    - '**/.DS_Store'
    - 'bin/**/*'
    - 'sbin/**/*'

Layout/EmptyLineAfterGuardClause: {Enabled: false}
Layout/EmptyLines: {Enabled: false}
Layout/LineLength: {Enabled: false}
Lint/Debugger: {Enabled: false}
Lint/EmptyBlock: {Enabled: false}
Lint/EmptyClass: {Enabled: false}
Lint/SuppressedException: {Enabled: false}
Metrics/AbcSize: {Enabled: false}
Metrics/BlockLength: {Enabled: false}
Metrics/CyclomaticComplexity: {Enabled: false}
Metrics/MethodLength: {Enabled: false}
Metrics/ModuleLength: {Enabled: false}
Metrics/PerceivedComplexity: {Enabled: false}
Naming/InclusiveLanguage: {Enabled: false}
Rails/BulkChangeTable: {Enabled: false}
Rails/CreateTableWithTimestamps: {Enabled: false}
Rails/I18nLocaleTexts: {Enabled: false}
Rails/ReversibleMigration: {Enabled: false}
Style/AccessorGrouping: {Enabled: false}
Style/BlockDelimiters: {Enabled: false}
Style/Documentation: {Enabled: false}
Style/FrozenStringLiteralComment: {Enabled: true, SafeAutoCorrect: false}
Style/MultilineBlockChain: {Enabled: false}
Style/RescueModifier: {Enabled: false}
Style/RescueStandardError: {Enabled: false}
Style/Semicolon: {Enabled: false}
Rails/Output: {Enabled: false}

